fullnameOverride: payment-service
component: api
partOf: spring-demo
version: 0.1.0-observability.9669693

replicaCount: 1

image:
  repository: $(REGISTRY_IMAGE_PREFIX)/payment-service
  tag: 0.1.0-observability.9669693
  digest: sha256:d6229ed30550d06cfe1d83ffc54590d826caca665f553f8d855a5b3d419b6c18
  pullPolicy: IfNotPresent

podAnnotations:
  linkerd.io/inject: enabled
  prometheus.io/scrape: "true"
  prometheus.io/path: /actuator/prometheus
  prometheus.io/port: "8080"

hostAliases:
  - ip: $(CLUSTER_B_INGRESS_IP)
    hostnames:
      - $(TEMPO_HOST)

terminationGracePeriodSeconds: 45

env:
  - name: APP_ENVIRONMENT
    value: lab
  - name: PAYMENT_API_VERSION
    value: 0.1.0
  - name: MANAGEMENT_OTLP_TRACING_ENDPOINT
    value: $(TEMPO_OTLP_ENDPOINT)
  - name: MANAGEMENT_TRACING_SAMPLING_PROBABILITY
    value: "1.0"

containerPort: 8080

service:
  enabled: true
  type: ClusterIP
  port: 80
  targetPort: http

pdb:
  enabled: true
  maxUnavailable: 1

startupProbe:
  httpGet:
    path: /actuator/health/liveness
    port: http
  failureThreshold: 30
  periodSeconds: 5

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: http
  periodSeconds: 10
  timeoutSeconds: 2

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: http
  periodSeconds: 20
  timeoutSeconds: 2

resources:
  requests:
    cpu: 100m
    memory: 384Mi
  limits:
    cpu: 1000m
    memory: 768Mi

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532

volumeMounts:
  - name: tmp
    mountPath: /tmp

volumes:
  - name: tmp
    emptyDir: {}

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: payment-service
