deployment:
  replicas: 2

ingressClass:
  enabled: true
  isDefaultClass: false
  name: traefik

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true
    ingressClass: traefik
    publishedService:
      enabled: true
  kubernetesGateway:
    enabled: false

service:
  enabled: true
  annotations:
    metallb.universe.tf/loadBalancerIPs: $(CLUSTER_B_INGRESS_IP)
  spec:
    type: LoadBalancer

logs:
  general:
    level: INFO

metrics:
  prometheus:
    service:
      enabled: true
