apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

helmCharts:
  - name: minio
    repo: https://charts.min.io/
    version: 5.4.0
    releaseName: minio
    namespace: observability
    valuesFile: values.yaml

resources:
  - secret.yaml
