apiVersion: v1
kind: Secret
metadata:
  name: minio-root
  namespace: observability
  annotations:
    k3s-lab.dev/note: "Lab-only credential. Replace with SealedSecrets or ExternalSecrets for real environments."
type: Opaque
stringData:
  rootUser: k3s-lab-minio
  rootPassword: k3s-lab-minio-password
