fullnameOverride: order-service
component: api
partOf: spring-demo
version: 0.1.0-observability.9669693

replicaCount: 1

image:
  repository: registry.b.lab.home/k3s-lab/order-service
  tag: 0.1.0-observability.9669693
  digest: sha256:f34ff9e237cff8bb35bade667ee74bf5818a6ab3e220141e935fec58260b7ce4
  pullPolicy: IfNotPresent

podAnnotations:
  linkerd.io/inject: enabled
  prometheus.io/scrape: "true"
  prometheus.io/path: /actuator/prometheus
  prometheus.io/port: "8080"

hostAliases:
  - ip: 192.168.50.245
    hostnames:
      - tempo.b.lab.home

terminationGracePeriodSeconds: 45

env:
  - name: APP_ENVIRONMENT
    value: lab
  - name: ORDER_API_VERSION
    value: 0.1.0
  - name: PAYMENT_API_VERSION
    value: 0.1.0
  - name: PAYMENT_SERVICE_URL
    value: http://payment-service
  - name: MANAGEMENT_OTLP_TRACING_ENDPOINT
    value: http://tempo.b.lab.home/v1/traces
  - name: MANAGEMENT_TRACING_SAMPLING_PROBABILITY
    value: "1.0"

containerPort: 8080

service:
  enabled: true
  type: ClusterIP
  port: 80
  targetPort: http

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: order.a.lab.home
      paths:
        - path: /
          pathType: Prefix

pdb:
  enabled: true
  maxUnavailable: 1

startupProbe:
  httpGet:
    path: /actuator/health/liveness
    port: http
  failureThreshold: 30
  periodSeconds: 5

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: http
  periodSeconds: 10
  timeoutSeconds: 2

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: http
  periodSeconds: 20
  timeoutSeconds: 2

resources:
  requests:
    cpu: 100m
    memory: 384Mi
  limits:
    cpu: 1000m
    memory: 768Mi

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532

volumeMounts:
  - name: tmp
    mountPath: /tmp

volumes:
  - name: tmp
    emptyDir: {}

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: order-service
