#!/usr/bin/env bash
# Pin the bridged interface (identified by MAC) to a static LAN IP via
# NetworkManager. Idempotent.
set -euo pipefail

: "${VM_MAC:?}"
: "${VM_IP:?}"
: "${PREFIX:?}"
: "${GATEWAY:?}"
: "${DNS:?}"
: "${DOMAIN:?}"

iface="$(ip -o link | awk -v mac="${VM_MAC,,}" 'tolower($0) ~ mac {print $2}' | tr -d ':')"
if [ -z "$iface" ]; then
  echo "could not find interface with MAC $VM_MAC" >&2
  ip -o link >&2
  exit 1
fi

con_name="lab-${iface}"
dns_csv="$(echo "$DNS" | tr ' ' ',')"

# remove any existing autogenerated profile for this device
nmcli -t -f NAME,DEVICE connection show | awk -F: -v d="$iface" '$2==d {print $1}' \
  | while read -r existing; do
      [ "$existing" = "$con_name" ] && continue
      nmcli connection delete "$existing" || true
    done

if nmcli -t -f NAME connection show | grep -qx "$con_name"; then
  nmcli connection modify "$con_name" \
    ipv4.addresses "${VM_IP}/${PREFIX}" \
    ipv4.gateway "$GATEWAY" \
    ipv4.dns "$dns_csv" \
    ipv4.dns-search "$DOMAIN" \
    ipv4.method manual \
    ipv6.method disabled
else
  nmcli connection add type ethernet \
    con-name "$con_name" \
    ifname "$iface" \
    ipv4.addresses "${VM_IP}/${PREFIX}" \
    ipv4.gateway "$GATEWAY" \
    ipv4.dns "$dns_csv" \
    ipv4.dns-search "$DOMAIN" \
    ipv4.method manual \
    ipv6.method disabled
fi

nmcli connection up "$con_name"
