#!/usr/bin/env bash
# Pin the bridged interface (identified by MAC) to a static LAN IP via
# NetworkManager. Idempotent.
set -euo pipefail

: "${VM_MAC:?}"
: "${VM_IP:?}"
: "${PREFIX:?}"
: "${GATEWAY:?}"
: "${DNS:?}"
: "${DOMAIN:?}"

iface="$(ip -o link | awk -v mac="${VM_MAC,,}" 'tolower($0) ~ mac {print $2}' | tr -d ':')"
if [ -z "$iface" ]; then
  echo "could not find interface with MAC $VM_MAC" >&2
  ip -o link >&2
  exit 1
fi

con_name="lab-${iface}"
dns_csv="$(echo "$DNS" | tr ' ' ',')"

has_expected_ip() {
  ip -o -4 addr show dev "$iface" \
    | awk -v expected="${VM_IP}/${PREFIX}" '$4 == expected { found = 1 } END { exit found ? 0 : 1 }'
}

connection_is_active() {
  nmcli -t -f NAME,DEVICE connection show --active \
    | awk -F: -v name="$con_name" -v dev="$iface" '$1 == name && $2 == dev { found = 1 } END { exit found ? 0 : 1 }'
}

# remove any existing autogenerated profile for this device
nmcli -t -f NAME,DEVICE connection show | awk -F: -v d="$iface" '$2==d {print $1}' \
  | while read -r existing; do
      [ "$existing" = "$con_name" ] && continue
      nmcli connection delete "$existing" || true
    done

if nmcli -t -f NAME connection show | grep -qx "$con_name"; then
  nmcli connection modify "$con_name" \
    ipv4.addresses "${VM_IP}/${PREFIX}" \
    ipv4.gateway "$GATEWAY" \
    ipv4.dns "$dns_csv" \
    ipv4.dns-search "$DOMAIN" \
    ipv4.method manual \
    ipv6.method disabled
else
  nmcli connection add type ethernet \
    con-name "$con_name" \
    ifname "$iface" \
    ipv4.addresses "${VM_IP}/${PREFIX}" \
    ipv4.gateway "$GATEWAY" \
    ipv4.dns "$dns_csv" \
    ipv4.dns-search "$DOMAIN" \
    ipv4.method manual \
    ipv6.method disabled
fi

if nmcli connection up "$con_name"; then
  exit 0
fi

echo "initial activation of $con_name failed; waiting for NetworkManager to settle" >&2
for _ in $(seq 1 10); do
  if connection_is_active && has_expected_ip; then
    echo "$con_name is active with ${VM_IP}/${PREFIX}" >&2
    exit 0
  fi

  sleep 2
  nmcli connection up "$con_name" && exit 0
done

echo "$con_name did not activate with ${VM_IP}/${PREFIX}" >&2
ip -br addr show "$iface" >&2 || true
nmcli -t -f NAME,DEVICE,STATE connection show --active >&2 || true
exit 1
