apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: observability-intake
  namespace: observability
spec:
  ingressClassName: traefik
  rules:
    - host: $(LOKI_HOST)
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loki
                port:
                  number: 3100
    - host: $(PROMETHEUS_HOST)
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-server
                port:
                  number: 80
    - host: $(TEMPO_HOST)
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tempo
                port:
                  number: 4318
